cp ./CPP-HelloWorld/text/* Pr0106/text/.
cp ./CPP-HelloWorld/text/* Pr0107/text/.
cp ./CPP-HelloWorld/text/* Pr0108/text/.
cp ./CPP-HelloWorld/text/* Pr0109/text/.
cp ./CPP-HelloWorld/text/* Pr0110/text/.
cp ./CPP-HelloWorld/text/* Pr0111/text/.
cp ./CPP-HelloWorld/text/* Pr0112/text/.
cp ./CPP-HelloWorld/text/* Pr0113/text/.
cp ./CPP-HelloWorld/text/* Pr0114/text/.
cp ./CPP-HelloWorld/text/* Pr0201/text/.
cp ./CPP-HelloWorld/text/* Pr0202/text/.
cp ./CPP-HelloWorld/text/* Pr0203/text/.
cp ./CPP-HelloWorld/text/* Pr0204/text/.
cp ./CPP-HelloWorld/text/* Pr0301/text/.
cp ./CPP-HelloWorld/text/* Pr0302/text/.
cp ./CPP-HelloWorld/text/* Pr0303/text/.
cp ./CPP-HelloWorld/text/* Pr0304/text/.
cp ./CPP-HelloWorld/text/* Pr0305/text/.
cp ./CPP-HelloWorld/text/* Pr0306/text/.
cp ./CPP-HelloWorld/text/* Pr0307/text/.
cp ./CPP-HelloWorld/text/* Pr0308/text/.
cp ./CPP-HelloWorld/text/* Pr0309/text/.
cp ./CPP-HelloWorld/text/* Pr0310/text/.
cp ./CPP-HelloWorld/text/* Pr0311/text/.
cp ./CPP-HelloWorld/text/* Pr0312/text/.
cp ./CPP-HelloWorld/text/* Pr0313/text/.
cp ./CPP-HelloWorld/text/* Pr0314/text/.
cp ./CPP-HelloWorld/text/* Pr0404/text/.
cp ./CPP-HelloWorld/text/* Pr0405/text/.
cp ./CPP-HelloWorld/text/* Pr0407/text/.
cp ./CPP-HelloWorld/text/* Pr0408/text/.
cp ./CPP-HelloWorld/text/* Pr0409/text/.
cp ./CPP-HelloWorld/text/* Pr0410/text/.
cp ./CPP-HelloWorld/text/* Pr0411/text/.
cp ./CPP-HelloWorld/text/* Pr0412/text/.
cp ./CPP-HelloWorld/text/* Pr0413/text/.
cp ./CPP-HelloWorld/text/* Pr0414/text/.
cp ./CPP-HelloWorld/text/* Pr0503/text/.
cp ./CPP-HelloWorld/text/* Pr0504/text/.
cp ./CPP-HelloWorld/text/* Pr0505/text/.
cp ./CPP-HelloWorld/text/* Pr0506/text/.
cp ./CPP-HelloWorld/text/* Pr0507/text/.
cp ./CPP-HelloWorld/text/* Pr0508/text/.
cp ./CPP-HelloWorld/text/* Pr0509/text/.
cp ./CPP-HelloWorld/text/* Pr0510/text/.
cp ./CPP-HelloWorld/text/* Pr0511/text/.
cp ./CPP-HelloWorld/text/* Pr0512/text/.
cp ./CPP-HelloWorld/text/* Pr0513/text/.
cp ./CPP-HelloWorld/text/* Pr0514/text/.
cp ./CPP-HelloWorld/text/* Pr0515/text/.
cp ./CPP-HelloWorld/text/* Pr0516/text/.
cp ./CPP-HelloWorld/text/* Pr0517/text/.
cp ./CPP-HelloWorld/text/* Pr0518/text/.
cp ./CPP-HelloWorld/text/* Pr0519/text/.
cp ./CPP-HelloWorld/text/* Pr0520/text/.
cp ./CPP-HelloWorld/text/* Pr0521/text/.
cp ./CPP-HelloWorld/text/* Pr0522/text/.
cp ./CPP-HelloWorld/text/* Pr0523/text/.
cp ./CPP-HelloWorld/text/* Pr0524/text/.
cp ./CPP-HelloWorld/text/* Pr0525/text/.
cp ./CPP-HelloWorld/text/* Pr0526/text/.
cp ./CPP-HelloWorld/text/* Pr0601/text/.
cp ./CPP-HelloWorld/text/* Pr0602/text/.
cp ./CPP-HelloWorld/text/* Pr0603/text/.
cp ./CPP-HelloWorld/text/* Pr0604/text/.
cp ./CPP-HelloWorld/text/* Pr0605/text/.
cp ./CPP-HelloWorld/text/* Pr0606/text/.
cp ./CPP-HelloWorld/text/* Pr0607/text/.
cp ./CPP-HelloWorld/text/* Pr0608/text/.
cp ./CPP-HelloWorld/text/* Pr0609/text/.
cp ./CPP-HelloWorld/text/* Pr0610/text/.
cp ./CPP-HelloWorld/text/* Pr0611/text/.
cp ./CPP-HelloWorld/text/* Pr0612/text/.
cp ./CPP-HelloWorld/text/* Pr0613/text/.
cp ./CPP-HelloWorld/text/* Pr0614/text/.
cp ./CPP-HelloWorld/text/* Pr0615/text/.
cp ./CPP-HelloWorld/text/* Pr0616/text/.
cp ./CPP-HelloWorld/text/* Pr0617/text/.
cp ./CPP-HelloWorld/text/* Pr0618/text/.
cp ./CPP-HelloWorld/text/* Pr0619/text/.
cp ./CPP-HelloWorld/text/* Pr0620/text/.
cp ./CPP-HelloWorld/text/* Pr0621/text/.
cp ./CPP-HelloWorld/text/* Pr0622/text/.
cp ./CPP-HelloWorld/text/* Pr0623/text/.
cp ./CPP-HelloWorld/text/* Pr0624/text/.
cp ./CPP-HelloWorld/text/* Pr0625/text/.
cp ./CPP-HelloWorld/text/* Pr0626/text/.
cp ./CPP-HelloWorld/text/* Pr0627/text/.
cp ./CPP-HelloWorld/text/* Pr0628/text/.
cp ./CPP-HelloWorld/text/* Pr0629/text/.
cp ./CPP-HelloWorld/text/* Pr0630/text/.
cp ./CPP-HelloWorld/text/* Pr0631/text/.
cp ./CPP-HelloWorld/text/* Pr0632/text/.
cp ./CPP-HelloWorld/text/* Pr0633/text/.
cp ./CPP-HelloWorld/text/* Pr0634/text/.
cp ./CPP-HelloWorld/text/* Pr0635/text/.
cp ./CPP-HelloWorld/text/* Pr0636/text/.
cp ./CPP-HelloWorld/text/* Pr0701/text/.
cp ./CPP-HelloWorld/text/* Pr0702/text/.
cp ./CPP-HelloWorld/text/* Pr0703/text/.
cp ./CPP-HelloWorld/text/* Pr0704/text/.
cp ./CPP-HelloWorld/text/* Pr0705/text/.
cp ./CPP-HelloWorld/text/* Pr0706/text/.
cp ./CPP-HelloWorld/text/* Pr0707/text/.
cp ./CPP-HelloWorld/text/* Pr0708/text/.
cp ./CPP-HelloWorld/text/* Pr0709/text/.
cp ./CPP-HelloWorld/text/* Pr0710/text/.
cp ./CPP-HelloWorld/text/* Pr0711/text/.
cp ./CPP-HelloWorld/text/* Pr0712/text/.
cp ./CPP-HelloWorld/text/* Pr0713/text/.
cp ./CPP-HelloWorld/text/* Pr0714/text/.
cp ./CPP-HelloWorld/text/* Pr0715/text/.
cp ./CPP-HelloWorld/text/* Pr0716/text/.
cp ./CPP-HelloWorld/text/* Pr0717/text/.
cp ./CPP-HelloWorld/text/* Pr0718/text/.
cp ./CPP-HelloWorld/text/* Pr0719/text/.
cp ./CPP-HelloWorld/text/* Pr0720/text/.
cp ./CPP-HelloWorld/text/* Pr0721/text/.
cp ./CPP-HelloWorld/text/* Pr0722/text/.
cp ./CPP-HelloWorld/text/* Pr0723/text/.
cp ./CPP-HelloWorld/text/* Pr0724/text/.
cp ./CPP-HelloWorld/text/* Pr0802/text/.
cp ./CPP-HelloWorld/text/* Pr0803/text/.
cp ./CPP-HelloWorld/text/* Pr0804/text/.
cp ./CPP-HelloWorld/text/* Pr0805/text/.
cp ./CPP-HelloWorld/text/* Pr0806/text/.
cp ./CPP-HelloWorld/text/* Pr0807/text/.
cp ./CPP-HelloWorld/text/* Pr0808/text/.
cp ./CPP-HelloWorld/text/* Pr0809/text/.
cp ./CPP-HelloWorld/text/* Pr0810/text/.
cp ./CPP-HelloWorld/text/* Pr0811/text/.
cp ./CPP-HelloWorld/text/* Pr0812/text/.
cp ./CPP-HelloWorld/text/* Pr0813/text/.
cp ./CPP-HelloWorld/text/* Pr0814/text/.
cp ./CPP-HelloWorld/text/* Pr0815/text/.
cp ./CPP-HelloWorld/text/* Pr0816/text/.
cp ./CPP-HelloWorld/text/* Pr0817/text/.
cp ./CPP-HelloWorld/text/* Pr0818/text/.
cp ./CPP-HelloWorld/text/* Pr0819/text/.
cp ./CPP-HelloWorld/text/* Pr0821/text/.
cp ./CPP-HelloWorld/text/* Pr0822/text/.
cp ./CPP-HelloWorld/text/* Pr0823/text/.
cp ./CPP-HelloWorld/text/* Pr0824/text/.
cp ./CPP-HelloWorld/text/* Pr0905/text/.
cp ./CPP-HelloWorld/text/* Pr0906/text/.
cp ./CPP-HelloWorld/text/* Pr0907/text/.
cp ./CPP-HelloWorld/text/* Pr0908/text/.
cp ./CPP-HelloWorld/text/* Pr0909/text/.
cp ./CPP-HelloWorld/text/* Pr0910/text/.
cp ./CPP-HelloWorld/text/* Pr0911/text/.
cp ./CPP-HelloWorld/text/* Pr0912/text/.
cp ./CPP-HelloWorld/text/* Pr0913/text/.
cp ./CPP-HelloWorld/text/* Pr0914/text/.
cp ./CPP-HelloWorld/text/* Pr0915/text/.
cp ./CPP-HelloWorld/text/* Pr0916/text/.
cp ./CPP-HelloWorld/text/* Pr1001/text/.
cp ./CPP-HelloWorld/text/* Pr1002/text/.
cp ./CPP-HelloWorld/text/* Pr1003/text/.
cp ./CPP-HelloWorld/text/* Pr1004/text/.
cp ./CPP-HelloWorld/text/* Pr1005/text/.
cp ./CPP-HelloWorld/text/* Pr1006/text/.
cp ./CPP-HelloWorld/text/* Pr1007/text/.
cp ./CPP-HelloWorld/text/* Pr1008/text/.
cp ./CPP-HelloWorld/text/* Pr1009/text/.
cp ./CPP-HelloWorld/text/* Pr1101/text/.
cp ./CPP-HelloWorld/text/* Pr1102/text/.
cp ./CPP-HelloWorld/text/* Pr1105/text/.
cp ./CPP-HelloWorld/text/* Pr1106/text/.
cp ./CPP-HelloWorld/text/* Pr1107/text/.
cp ./CPP-HelloWorld/text/* Pr1108/text/.
cp ./CPP-HelloWorld/text/* Pr1109/text/.
cp ./CPP-HelloWorld/text/* Pr1201/text/.
cp ./CPP-HelloWorld/text/* Pr1202/text/.
cp ./CPP-HelloWorld/text/* Pr1301/text/.
cp ./CPP-HelloWorld/text/* Pr1302/text/.
cp ./CPP-HelloWorld/text/* Pr1303/text/.
cp ./CPP-HelloWorld/text/* Pr1304/text/.
cp ./CPP-HelloWorld/text/* Pr1305/text/.
cp ./CPP-HelloWorld/text/* Pr1306/text/.
cp ./CPP-HelloWorld/text/* Pr1401/text/.
cp ./CPP-HelloWorld/text/* Pr1402/text/.
cp ./CPP-HelloWorld/text/* Pr1403/text/.
cp ./CPP-HelloWorld/text/* Pr1404/text/.